//! Page footer with project links and license badge.

use maud::{html, Markup};

pub fn render() -> Markup {
    html! {
        footer {
            div class="footer-links" {
                a href="https://github.com/JackDanger/open-english-pronouncing-dictionary"
                  target="_blank" rel="noopener" { "GitHub" }
                a href="https://crates.io/crates/open-english-pronouncing-dictionary"
                  target="_blank" rel="noopener" { "crates.io" }
                a href="https://github.com/JackDanger/phonetics"
                  target="_blank" rel="noopener" { "phonetics-rs" }
            }
            div {
                span class="license-badge" { "CC BY-SA 4.0" }
                "  Sources: Misaki · CMU · WikiPron"
            }
            div {
                "Generated by "
                span class="mono" { "site-gen" }
                " (OpenEPD)"
            }
        }
    }
}
